### ISSUE TITLE
America/Panama is missing?

### ISSUE THREAD

**Issue by crowz4k** [mattjohnsonpint/TimeZoneConverter#100]
I noticed that America/Panama is missing?

**Comment by mattjohnsonpint** [comment]
Works for me.   https://dotnetfiddle.net/7Nyl24

Can you offer code that reproduces the issue?

**Comment by crowz4k** [comment]
Ah sorry, my bad I was using TZConvert.KnownWindowsTimeZoneIds and extracting IANA.
