### ISSUE TITLE
Antarctica/Troll fails to convert with TZConvert.GetTimeZoneInfo

### ISSUE THREAD

**Issue by ademchenko** [mattjohnsonpint/TimeZoneConverter#101]
TimeZoneConverter of version 3.5.0 contains "Antarctica/Troll" in TZConvert.KnownIanaTimeZoneNames. As far as I understand it should imply that TZConvert.GetTimeZoneInfo("Antarctica/Troll") call has to be successful. 
But: it raises TimeZoneNotFoundException in Windows 10 environment.

**Comment by bartlomiej1gorski** [comment]
Duplicate of #62
