### ISSUE TITLE
System.TimeZoneNotFoundException: Exception of type 'System.TimeZoneNotFoundException' was thrown.

### ISSUE THREAD

**Issue by logeshpalani32** [mattjohnsonpint/TimeZoneConverter#103]
When am trying to get timezoneinfo using below code, it throws not found 

`TimeZoneInfo timeZoneInfo = TZConvert.GetTimeZoneInfo("(US & Canada)    Central Standard Time");`

exception
_System.TimeZoneNotFoundException: Exception of type 'System.TimeZoneNotFoundException' was thrown._

**Comment by mattjohnsonpint** [comment]
That's because you supplied a display name, not an identifier.  Only valid IANA or Windows time zone IDs are accepted.
