### ISSUE TITLE
Misleading info on .NET 6 in README

### ISSUE THREAD

**Issue by alex-jitbit** [mattjohnsonpint/TimeZoneConverter#109]
.NET 6 does not have a built-in analog for `TZConvert.KnownWindowsTimeZoneIds` so the info in the readme "you don't need this library in .net 6" is a little bit misleading.

On *nix there's no way to list available time zones in Windows format

P.S. My app is cross-platform and I need consistent timezone list between two platforms in the UI (dropdown list). That is why I keep using this library even under .NET 6

P.P.S. Also Microsoft's "App-local ICU" mode is a little buggy and crashes on some platforms. Please keep this library alive

**Comment by jochenjonc** [comment]
Yes, indeed the info is very misleading. After some tests, I noticed that next to .NET 6 you also need to run it on a newer/updated version of Windows.

I have issues with Windows 2016 and Windows 2019 servers.

I found that you at least need Windows 10 version 1903 (may 2019 update), see https://docs.microsoft.com/en-us/windows/win32/intl/international-components-for-unicode--icu-#version-1903-may-2019-update.

**Comment by alex-jitbit** [comment]
@jochenjonc yes, indeed,

And on Linux you need `libicu` installed which is not always the case.

Which just proves that this library is awesome! ❤

**Comment by sykesbPragmatics** [comment]
Additionally this is not possible with Blazor WebAssembly because the client does not have access to the entire list of time zones.  If the string being checked is Windows based, it fails since it cannot find the time zone information.  I had to include this package in order to convert to IANA before getting the TimeZoneInfo.

**Comment by mattjohnsonpint** [comment]
I've updated the readme.  Feel free to send a PR if you feel like adding any more specific wording. 😜
