### ISSUE TITLE
Missing support for Asia/Kolkata

### ISSUE THREAD

**Issue by schueppi89** [mattjohnsonpint/TimeZoneConverter#112]

**Comment by mattjohnsonpint** [comment]
Seems working fine to me:
https://dotnetfiddle.net/3KF3R3

If you like, please provide code that fails and I will re-open.  Thanks.

**Comment by schueppi89** [comment]
Sorry for the issue. It was my bad. There was a bug on my side.

**Comment by mattjohnsonpint** [comment]
No problem. Thanks!
