### ISSUE TITLE
Missing America/Fort_Wayne alias

### ISSUE THREAD

**Issue by lisa-reynolds** [mattjohnsonpint/TimeZoneConverter#115]
The America/Fort_Wayne to America/Indiana/Indianapolis link worked correctly in 3.1.0 but seems to be missing in 3.5.0 onward. It's still [in the source data](http://ftp.iana.org/tz/tzdb-2022a/backward), but America/Indiana/Indianapolis is no longer present in the mapping so the link is not created.

**Comment by IronSean** [comment]
@mattjohnsonpint @fernandolguevara Any updates on this? This is breaking in our code now too (in a very unhelpful `TimeZoneNotFoundException: Exception of type 'System.TimeZoneNotFoundException' was thrown.` exception from `GetTimeZoneInfo` which doesn't tell us which timezone was the problem and had us manually testing all our DB values until we found the offending one then found this comment.
