### ISSUE TITLE
Upgrading to v6.0.1 and using TimeZoneNames 5.0.1

### ISSUE THREAD

**Issue by gjdownes** [mattjohnsonpint/TimeZoneConverter#130]
Firstly, thank you for the time you put into maintaining this library. It's a core component of our application and served us well for years.

I'm looking to upgrade to v6.0.1; I'm wondering if I can use that in tandem with v5.0.1 of the TimeZoneNames library or if we should be expecting a version bump for that in the near future. My primary concern is supporting the 2022c TZDB update consistently across libraries.

Thanks

**Comment by mattjohnsonpint** [comment]
I will have a TimeZoneNames update soon as well. But the current versions should be compatible.

**Comment by mattjohnsonpint** [comment]
TimeZoneNames 6.0.0 has finally been released.  Thanks for your patience!
