### ISSUE TITLE
Performance degraded randomly with .NET 6 migration

### ISSUE THREAD

**Issue by pil0t** [mattjohnsonpint/TimeZoneConverter#132]
After migration to .NET 6 simple usage 
`var timeZoneInfo = TZConvert.GetTimeZoneInfo(timeZone);`
in some cases takes few seconds.

In 99% of cases it executes in under 0.01 ms, but sometimes it takes much more (my current "record" is about 5782.5398 ms)

We have validator, that executes `GetTimeZoneInfo` method to ensure we have specific timezone and we log it execution time.
Before migration (.NET5 -> .NET6) it also had random degradation of performance, but all "slow" executions was below 1000 ms, and we didn't noticed them. 

After migration we faced with increased number of 1000 ms and more (up to almost 6 seconds!) random slow executions.

**Comment by mattjohnsonpint** [comment]
Thanks for reporting this.  I'll need a bit more to go on though.  Can you provide the validator you spoke of, or sample code that is intermittently slow?

I do have some rudimentary perf tests in the repo here:
https://github.com/mattjohnsonpint/TimeZoneConverter/blob/main/test/TimeZoneConverter.Tests/TimeZoneInfoPerfTests.cs

So far they haven't shown they type of problem you mentioned.

I would also be grateful if anyone feels up for adding true [`Benchmark.NET`](https://github.com/dotnet/BenchmarkDotNet) tests.

**Comment by mattjohnsonpint** [comment]
Hi, just checking in - are you able to provide any code that demonstrates?  Thanks.

**Comment by mattjohnsonpint** [comment]
Also, can you please confirm which version of TimeZoneConverter you are testing with?  Hopefully the latest. Thanks.

**Comment by pil0t** [comment]
@mattjohnsonpint sorry for delay, we have quite straightforward code, like:
```
    internal class CultureSettingValidator : ISettingValidator<ICultureSettings>
    {
        public void Validate(ICultureSettings item)
        {
            if (string.IsNullOrWhiteSpace(item.TimeZone))
            {
                throw new ValidationException("TimeZone must be specified!");
            }

            // We just need to ensure conversion happens
            try
            {
                var timeZoneInfo = TZConvert.GetTimeZoneInfo(item.TimeZone);
            }
            catch (TimeZoneNotFoundException)
            {
                throw new ValidationException($"TimeZone {item.TimeZone} not found!");
            }
        }
    }
```

I also tried to reproduce this as specific thing, but was not succeed with this.

Only thing I have right now, logs, that such validator executes for very long time in certain cases (rare cases actually).

**Comment by mattjohnsonpint** [comment]
FWIW, I ran [this test](https://github.com/mattjohnsonpint/TimeZoneConverter/blob/9112e5fcd4edbbfb8ff85eb4ffa4a2d039880bc7/test/TimeZoneConverter.Tests/TimeZoneInfoPerfTests.cs#L12-L24) overnight in a repeat-until-fail loop.  It ran for over 12 hours without failure.

**Comment by pil0t** [comment]
In my case on production environment (with bigger load) we almost have no such cases, and in Test/Dev environment with relatively small RPS we experience this sometimes (actually quite rare)

**Comment by mattjohnsonpint** [comment]
Does it happen when you are debugging while in an IDE?  If so, it would be super helpful to pause the app when it is hanging and grab a stack trace that includes `TimeZoneConverter`.

**Comment by pil0t** [comment]
nop, this is run in AWS ECS, here some logs statistics, showing execution time of the code above:
![image](https://user-images.githubusercontent.com/820134/201731095-418232f5-a039-4fb6-bbec-d316fb112395.png)

**Comment by mattjohnsonpint** [comment]
And how do you know that TimeZoneConverter is what is causing the slow times?

**Comment by mattjohnsonpint** [comment]
Also, what OS is that running on, and are you passing primarily IANA ids, Windows ids, or a mix of both?

**Comment by pil0t** [comment]
It's running in Linux containers in AWS ECS, most cases are requesting by name like `"Asia/Singapore"`

Also, I looksed at logs one more time, and found interesting thing:
looks like most of 'long runs' are happening after long time no-usage of this feature.
So, looks like it running first time after restart or maybe after big delay (hours) of running service and no usage of this method.

Not sure how to reproduce this issue, if there any tools to simulate something like this.

**Comment by mattjohnsonpint** [comment]
One thing you could do to narrow it down would be to change your code to something like this:

```csharp
if (!TZConvert.KnownIanaTimeZoneNames.Contains(item.TimeZone) &&
    !TZConvert.KnownWindowsTimeZoneIds.Contains(item.TimeZone))
{
    throw new ValidationException($"TimeZone {item.TimeZone} not found!");
}
```

That would be more efficient, as it would eliminate actually populating a `TimeZoneInfo` object.  Both of those collections are implemented as `HashSet<string>`, so the lookup should be fast.

If it's still intermittently slow after that, then it's more likely to be caused when we populate the internal data during static initialization, which would align more with your findings.

I'll also do some testing on Linux containers.  Are you using one of the official .NET docker images such as `mcr.microsoft.com/dotnet/runtime:6.0`, or something custom? And if custom, what Linux OS and version please?  And are you installing `tzdata` manually into the container or not?  Just want to get a similar setup to yours.  Thanks.

**Comment by pil0t** [comment]
Default images, used.
Just tried with very simple case:
```
using System.Diagnostics;
using TimeZoneConverter;

Console.WriteLine("Hello, World!");
var stopwatch = Stopwatch.StartNew();
var result = TZConvert.GetTimeZoneInfo("Asia/Singapore");
stopwatch.Stop();
Console.WriteLine($"Executed in: {stopwatch.Elapsed.TotalMilliseconds} ms");
```

On my local machine, if `run` (no debug) from rider it takes ~80 ms (executed few times, usually 70 - 85 ms)

Also tried this with docker (enable Linux containers with default rider template), and bit surprized:
```
D:\work\TestTZConvert>docker run 869                                                                                                                                                                    Hello, World!                                                                                                                                                                                           Executed in: 501.0136 ms                                                                                                                                                                                                                                                                                                                                                                                        D:\work\TestTZConvert>docker run 869                                                                                                                                                                    Hello, World!                                                                                                                                                                                           Executed in: 466.8359 ms                                                                                                                                                                                                                                                                                                                                                                                        D:\work\TestTZConvert>docker run 869                                                                                                                                                                    Hello, World!                                                                                                                                                                                           Executed in: 461.0567 ms                                                                                                                                                                                                                                                                                                                                                                                        D:\work\TestTZConvert>docker run 869                                                                                                                                                                    Hello, World!                                                                                                                                                                                           Executed in: 535.2365 ms                                                                                                                                                                                                                                                                                                                                                                                        D:\work\TestTZConvert>docker run 869                                                                                                                                                                    Hello, World!                                                                                                                                                                                           Executed in: 499.5568 ms                                
````

So, looks like the problem is in init in docker envirionemnt.

**Comment by mattjohnsonpint** [comment]
Ok.  I'll do some testing with Docker.  Thanks!

Another thing you could do is remove TimeZoneConverter from your project entirely.  That would help you more than me, but is probably worth doing and would likely solve your issue.  😅 

At least it would tell us if it's this library or .NET itself.

```csharp
try
{
    var timeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById(item.TimeZone);
}
catch (TimeZoneNotFoundException)
{
    throw new ValidationException($"TimeZone {item.TimeZone} not found!");
}
```

This will work with IANA IDs for .NET 6 on Linux as long as `tzdata` is available, and will also handle Windows IDs when ICU is available.  The default Debian-based images include both.  If you're using Alpine images you may have to install them manually.

**Comment by pil0t** [comment]
Yeah, good catch 😆 ! 

Previously we used mix of different formats and migrated to single one, but still used TZConvert. Previously there no way to use buildin `TimeZoneInfo.FindSystemTimeZoneById` with all formats and all OS.
