### ISSUE TITLE
Not returning correct sub time zone

### ISSUE THREAD

**Issue by dalvirsaini** [mattjohnsonpint/TimeZoneConverter#134]
var tz = TZConvert.WindowsToIana("Romance Standard Time");
 why its returning "Europe/Paris"
 instead of Europe/Madrid
is there anything wrong here? or there is any bug in this library?

**Comment by mattjohnsonpint** [comment]
It is returning the correct result, [as per the CLDR source data](https://github.com/unicode-org/cldr/blob/cb8467e1f828f5f28449ca133573be42281c2be2/common/supplemental/windowsZones.xml#L340-L345):

```xml
<!-- (UTC+01:00) Brussels, Copenhagen, Madrid, Paris -->
<mapZone other="Romance Standard Time" territory="001" type="Europe/Paris"/>
<mapZone other="Romance Standard Time" territory="BE" type="Europe/Brussels"/>
<mapZone other="Romance Standard Time" territory="DK" type="Europe/Copenhagen"/>
<mapZone other="Romance Standard Time" territory="ES" type="Europe/Madrid Africa/Ceuta"/>
<mapZone other="Romance Standard Time" territory="FR" type="Europe/Paris"/>
```

This means `Europe/Paris` is the default when a territory code is not specified.  If you want `Europe/Madrid`, then you have to supply `"ES"` as the territory code.

```csharp
var tz = TZConvert.WindowsToIana("Romance Standard Time", "ES");
```
