### ISSUE TITLE
GetTimeZoneInfo "Etc/GMT-1" returns GMT+1

### ISSUE THREAD

**Issue by FrankPfattheicher** [mattjohnsonpint/TimeZoneConverter#138]
var zone = TZConvert.GetTimeZoneInfo("Etc/GMT-1");

returns "(UTC+01:00) West-Zentralafrika"

**Comment by mattjohnsonpint** [comment]
Yes, that is the correct conversion.

https://github.com/unicode-org/cldr/blob/c59b4e947ebd48250dee52c62f56c069cc6a2d4c/common/supplemental/windowsZones.xml#L369


If your question was about the sign inversion, that is expected:

https://en.wikipedia.org/wiki/Tz_database#Area

> The special area of "Etc" is used for some administrative zones, particularly for "Etc/UTC" which represents Coordinated Universal Time. In order to conform with the POSIX style, those zone names beginning with "Etc/GMT" have their sign reversed from the standard ISO 8601 convention. In the "Etc" area, zones west of GMT have a positive sign and those east have a negative sign in their name (e.g "Etc/GMT-14" is 14 hours ahead of GMT).

Keep in mind that `Etc/GMT±X` zones are intended for edge cases such as time zones for ships at sea.  You should not use them for most locations on land.

**Comment by FrankPfattheicher** [comment]
Thank you for clarification.
