### ISSUE TITLE
Issue in America/Mexico_City

### ISSUE THREAD

**Issue by jaimeorteaga317** [mattjohnsonpint/TimeZoneConverter#140]
Hola he visto un error que me esta generando la librería, no es un error de código, es un problema con el horario de verano recien aplicado el dia de hoy 2/04/2023 a las 02:00 am

Display Name: (UTC-06:00) Guadalajara, Mexico City, Monterrey 
Standard Name: Central Standard Time (Mexico)  
Daylight Name: Central Daylight Time (Mexico)   
Supports DST: Yes
UTC Standard Offset: -06:00
UTC Daylight Offset:  -06:00              

El horario de verena al parecer es el que genero el problema, se realizara alguna actualizacion o ya se detecto este problema?

-----

Hello, I have seen an error that the library is generating, it is not a code error, it is a problem with the summer time recently applied today 04/2/2023 at 02:00 am

Display Name: (UTC-06:00) Guadalajara, Mexico City, Monterrey
Standard Name: Central Standard Time (Mexico)
Daylight Name: Central Daylight Time (Mexico)
Supports DST: Yes
UTC Standard Offset: -06:00
UTC Daylight Offset: -06:00

The summer time apparently is the one that generated the problem, will an update be made or has this problem already been detected?

**Comment by mattjohnsonpint** [comment]
I'm not sure what problem you are referring to?  The function of _this_ library is to convert the IANA time zone ID `"America/Mexico_City"` to the Windows time zone ID `"Central Standard Time (Mexico)"`.

Also, Mexico abolished DST for most regions in 2023.  See https://www.timeanddate.com/news/time/mexico-abolishes-dst-2022.html

If you're asking about the Windows time zone data itself, that is maintained by Microsoft - not this library.

See also https://techcommunity.microsoft.com/t5/daylight-saving-time-time-zone/mexico-2023-time-zone-updates-now-available/ba-p/3749684

Thanks.
