### ISSUE TITLE
dotnet newbie question

### ISSUE THREAD

**Issue by rtruss** [mattjohnsonpint/TimeZoneConverter#141]
I am looking to utilize this via powershell to auto update timezone on new computer builds using your tool.  I am having a hard time with understanding how to use the items in your example usage section.  We do not do much .net work in our company so please be gentle :).

**Comment by mattjohnsonpint** [comment]
This library doesn't set the computer's time zone settings.

Did you have a specific question about the usage of this library?

**Comment by rtruss** [comment]
that was what I was going to do use it to change timezones.  Thanks for clarifying what it does.   Have a great day.

My question was how to use the .net cmdline code as I am not familiar with it but being I cannot use this for what I was thinking its a moot point.


Thank You,







Roger Truss

End User Computing Engineer

***@***.***

[cid:36050380-c55f-4717-9f9f-85f323dbbd8b]<https://www.brunswick.com>
***@***.***>

(P) +1 920-924-1732

(M) +1 920-203-0625

(F) +1 920-924-1194

(Mitel) 7555-1732

________________________________
