### ISSUE TITLE
Time zones not being recognized or being return incorrectly even though mappings exist

### ISSUE THREAD

**Issue by rezlam** [mattjohnsonpint/TimeZoneConverter#146]
During our development process, I found 3 inconsistencies in the library, when trying to convert from IANA to Windows: 

Looking at Mapping.csv and TimeZoneConverter.DataBuilder/Program.cs, when trying to get the Windows time zone for "America/Ciudad_Juarez" it should return "Mountain Standard Time", but 

`TZConvert.TryIanaToWindows(@"America/Ciudad_Juarez", out var winTimeZoneId)`

returns false.

On a similar fashion `TZConvert.TryIanaToWindows` for the IANA IDs below is returning the incorrect values, even though mappings exist and are correct on Mapping.csv and TimeZoneConverter.DataBuilder/Program.cs

"America/Chihuahua" should return "Central Standard Time (Mexico)", but it's returning "Mountain Standard Time (Mexico)"
"America/Ojinaga" should return "Central Standard Time", but it's returning "Mountain Standard Time"

**Comment by mattjohnsonpint** [comment]
Hi. You appear to have TimeZoneConverter version version 6.0.1 or older.  The changes for Mexican time zones were included in the latest release, 6.1.0.  Please update, and you will find the results exactly as you expected.

Thanks.
