### ISSUE TITLE
Wrong offset for Pacific/Fiji timezone in Unix .Net 6 docker image.

### ISSUE THREAD

**Issue by dynamikus** [mattjohnsonpint/TimeZoneConverter#148]
Hi, 
Most likely this is not a problem with your library but I am curious as to why this is happening because I thought the library embeds it is own Tz Database.

I am using the latest version  6.1.0 of the TimeZoneConverter library.

Pacific/Fiji gives the wrong offset for a given date 2023-12-13T00:00:00 
Fiji stopped observing daylight savings in 2021 but I am getting +13 on an older Unix Docker Images.

Gives the wrong offset  +13
```cs
// OSVersion Unix 5.10.176.0 .NET 6  shows the offset as +13
 var fijiTz = TZConvert.GetTimeZoneInfo("Pacific/Fiji");
 var dt = DateTimeOffset.Parse("2023-12-13T00:00:00+12:00");
var tzOffset = fijiTz.GetUtcOffset(dt);  //  +13
```

Works fine +12
```cs
// OSVersion Unix 5.15.133.1 .NET 6   shows the offset as +12
 var fijiTz = TZConvert.GetTimeZoneInfo("Pacific/Fiji");
 var dt = DateTimeOffset.Parse("2023-12-13T00:00:00+12:00");
var tzOffset = fijiTz.GetUtcOffset(dt);  //  +12
```

**Comment by mattjohnsonpint** [comment]
Hi.  TimeZoneConverter only contains mappings of the IDs themselves - not the actual time zone offset information.  When you call `TZConvert.GetTimeZoneInfo`, it's a shortcut to retrieve the `TimeZoneInfo` object for .NET of either `Pacific/Fiji` (IANA) or `Fiji Standard Time` (Windows) depending on which OS is being used.  Ultimately, the `TimeZoneInfo` object is retrieved from .NET itself, similarly as if you had called `TimeZoneInfo.FindSystemTimeZoneById`.

On Unix systems, .NET still takes the offsets and DST data from the actual IANA `tzdata`.  Thus, if you want current data, you should update the `tzdata` package for your operating system.  For example, on Ubuntu, `apt-get update ; apt-get install tzdata`.

**Comment by mattjohnsonpint** [comment]
There are some other examples of installing `tzdata` for various Linux distros from within a docker file here:
https://dev.to/0xbf/set-timezone-in-your-docker-image-d22

**Comment by dynamikus** [comment]
Thank you @mattjohnsonpint 
I appreciate your response.
