### ISSUE TITLE
Error ConvertTime 'Africa/Casablanca' Ramadan

### ISSUE THREAD

**Issue by Pingouf** [mattjohnsonpint/TimeZoneConverter#150]
I have a problem when i use TimeZoneInfo.ConvertTime('11/03/2024 00:00:00 UTC' , TimeZoneInfo  ((UTC+01:00) Casablanca))

Since 11/03/2024 it's Ramadan in Morocco so they're on TimeZone UTC + 0 . 

Why ConverTime give me 11/03/2024 01:00:00 instead of 11/03/2024 00:00:00 ?

Thanks

**Comment by mattjohnsonpint** [comment]
Hi.  This library doesn't provide the `TimeZoneInfo` object.  That's part of .NET.  Thanks.
