### ISSUE TITLE
Consider returning a custom time zone for Troll Station Antarctica on Windows

### ISSUE THREAD

**Issue by mattjohnsonpint** [mattjohnsonpint/TimeZoneConverter#62]
`TZConvert.IanaToWindows("Antarctica/Troll")` fails because there's nothing to map it to.  Windows doesn't support that time zone, due to its complex rules.

However, we should be able to have `TZConvert.GetTimeZoneInfo("Antarctica/Troll")` work regardless of platform.  On Windows it can return a custom time zone created with `TimeZoneInfo.CreateCustomTimeZone`.

**Comment by ntimmerman** [comment]
Or just put it in documentation.

**Comment by mattjohnsonpint** [comment]
@ntimmerman - I added some notes about that to the readme.  But I'll keep this open for one day when I feel like playing with custom time zones. 😉

**Comment by mattjohnsonpint** [comment]
Added with 7ff330ba109501f2f40e537147023c2b7da7d03c
