### ISSUE TITLE
Feature request: Expose private maps

### ISSUE THREAD

**Issue by jmaurier** [mattjohnsonpint/TimeZoneConverter#68]
The Iana, Windows, and Rails maps are all private in the TZConvert class. It would be nice to be able to use Linq for working with subsets of the mappings instead of rebuilding the key-value sets over again.

Currently, if I want to get the conversion for all the time zones in a single country, a map is created by the data loader, then I use a subset of iana id's that comes from the `KnownIanaTimeZoneNames` member to create a new map to the windows equivalents.

`IanaMap`, `WindowsMap`, and `RailsMap` could be exposed as [ReadOnlyDictionary<TKey, TValue>](https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.readonlydictionary-2?view=netcore-3.1) and the `InverseRailsMap` would need the something like `ReadOnlyCollection` for it's inner list.

**Comment by mj1856** [comment]
I'll consider this.  Thanks.

**Comment by msawczyn** [comment]
I'd like to second this motion. With `WindowsMap` publicly exposed, an application could also filter by territory, getting (for instance) all Windows US timezones and their IANA mappings.

**Comment by mattjohnsonpint** [comment]
I've decided not to expose the maps themselves.   However, there is now a method `GetIanaTimeZoneNamesByTerritory` that will help you get all the time zones in a specific country.  Hope that helps.

Thanks.
