### ISSUE TITLE
US Eastern Standard Time vs. Eastern Standard Time

### ISSUE THREAD

**Issue by filipnavara** [mattjohnsonpint/TimeZoneConverter#92]
I did a cross check with our data in eM Client to verify the mapping. Most of the differences were harmless (different names with same offsets), some of them were mistakes in our mapping. There was however something that caught my attention. For couple of the time zones we use "US Eastern Standard Time" whereas TimeZoneConverter uses "Eastern Standard Time":

America/Detroit
America/Indiana/Petersburg
America/Indiana/Vincennes
America/Indiana/Winamac
America/Kentucky/Louisville
America/Kentucky/Monticello

Specifically for Indiana it could have some historical difference (https://stackoverflow.com/questions/11457040/us-eastern-standard-time-vs-eastern-standard-time-in-net) in time zone observation which made me wonder which mapping is the correct one.

**Comment by filipnavara** [comment]
Additionally, these mappings look fishy, but could actually be correct:

| IANA | eM Client | TimeZoneConverter |
| ------------- | ---------- | ----------- |
| CET | Central Europe Standard Time | Romance Standard Time |
| EET | E. Europe Standard Time | GTB Standard Time |
| EST | Eastern Standard Time | SA Pacific Standard Time |

**Comment by mattjohnsonpint** [comment]
"Eastern Standard Time" is correct for the ones in your first list.

https://github.com/unicode-org/cldr/blob/acd323bdd2fcc7e518ffacc06ef2d605ed9a4750/common/supplemental/windowsZones.xml#L137

```xml
<mapZone other="Eastern Standard Time" territory="US" type="America/New_York America/Detroit America/Indiana/Petersburg America/Indiana/Vincennes America/Indiana/Winamac America/Kentucky/Monticello America/Louisville"/>
```

Contrast that with "US Eastern Standard Time":

https://github.com/unicode-org/cldr/blob/acd323bdd2fcc7e518ffacc06ef2d605ed9a4750/common/supplemental/windowsZones.xml#L150

```xml
<mapZone other="US Eastern Standard Time" territory="US" type="America/Indianapolis America/Indiana/Marengo America/Indiana/Vevay"/>
```

There are complex reasons.  See https://en.wikipedia.org/wiki/Time_in_Indiana#History

**Comment by mattjohnsonpint** [comment]
On the second list,  There aren't any official mappings for those.  I map them as follows:

https://github.com/mattjohnsonpint/TimeZoneConverter/blob/main/src/TimeZoneConverter.DataBuilder/Program.cs#L63-L67

```csharp
// Add a few aliases for IANA abbreviated zones not tracked by CLDR
aliases.Add("Europe/Paris,CET");
aliases.Add("Europe/Bucharest,EET");
aliases.Add("Europe/Berlin,MET");
aliases.Add("Atlantic/Canary,WET");
```

**Comment by filipnavara** [comment]
Thanks for looking into it. I really appreciate the additional verification.
