### ISSUE TITLE
Add the option to return the actual CLDR Unicode Golden mapping tz, instead of resolving the alias to canonical IANA tz

### ISSUE THREAD

**Issue by theyetiman** [mattjohnsonpint/TimeZoneConverter#94]
https://github.com/mattjohnsonpint/TimeZoneConverter/blob/f90679a15b999e7755d0ee1655559615bfdea6cc/src/TimeZoneConverter/DataLoader.cs#L36

It looks like when you map from Windows to IANA, this library auto-resolves any potential IANA alias to its canonical. One could argue this is both good and bad, depending on the use case.

In my use case, the Unicode CLDR mapping xml file is the source of truth for multiple systems, so when I map from Windows to IANA, I need to get the actual golden/001 tz from the CLDR xml mapping file, **even if it's an alias**.

Example:

See the mapping here https://github.com/unicode-org/cldr/blob/cb6444dab2cc094de9c2e37a66d52121b84fadcc/common/supplemental/windowsZones.xml#L149

It's for Windows zone "US Eastern Standard Time", which has a golden/001 IANA zone of "America/Indianapolis". That's the zone string I need to be compatible with other systems.

This library gets that value, then goes on to resolve the alias to "America/Indiana/Indianapolis".

`"America/Indianapolis" != "America/Indiana/Indianapolis"`

It would be hugely beneficial to provide a mechanism where you could choose if you want to resolve any aliases or not. E.g. a boolean flag supplied to the method call.

**Comment by mattjohnsonpint** [comment]
Agreed.  Actually, *not* resolving links should be the default behavior.  I will make this breaking change in the next release, with an option to obtain the previous behavior for those that want it.

**Comment by mattjohnsonpint** [comment]
Actually, after reviewing closer it seems that we need a few different options.  Here's my plan, with some examples for each option:

- **"Default" Mode**
  Return an IANA canonical value for the conversion, except for the case when an alias is more regionally appropriate for the conversion.

  Examples:
    - "India Standard Time" => "Asia/Kolkata"
    - "SA Western Standard Time" (AG) => "America/Antigua"

- **"Canonical" Mode**
   Always return an IANA canonical value.  (The current behavior.)

  Examples:
  - "India Standard Time" => "Asia/Kolkata"
  - "SA Western Standard Time" (AG) => "America/Puerto_Rico"

- **"Original" Mode** 
  Always return the exact value from the CLDR mapping.

  Examples:
  - "India Standard Time" => "Asia/Calcutta"
  - "SA Western Standard Time" (AG) => "America/Antigua"
