### ISSUE TITLE
"South Sudan Standard Time" timezone convert error

### ISSUE THREAD

**Issue by turhany** [mattjohnsonpint/TimeZoneConverter#96]
I get it when try to convert  "TimeZoneInfo.GetSystemTimeZones()" with "TZConvert.WindowsToIana" method.
"South Sudan Standard Time" was not recognized as a valid Windows time zone ID.

**Comment by mattjohnsonpint** [comment]
FYI, It should map to `"Africa/Juba"`.

**Comment by mattjohnsonpint** [comment]
CLDR Issue: https://unicode-org.atlassian.net/browse/CLDR-14653
CLDR PR: https://github.com/unicode-org/cldr/pull/1193

**Comment by turhany** [comment]
Thank you, i change my flow with "TryWindowsToIana" for now it solve my problem, after your release i will update nuget package.

**Comment by mattjohnsonpint** [comment]
Fixed in TimeZoneConverter release 3.5.0.

Thanks again!
