### ISSUE TITLE
"South Sudan Standard Time"  results in TimeZoneNotFoundException in .NET 6 Preview 3

### ISSUE THREAD

**Issue by zoinkydoink** [mattjohnsonpint/TimeZoneConverter#97]
Just converted the following code to .NET 6 preview there and the following fails when it tries to convert one of the items gotten from` .KnownWindowsTimeZoneIds`
```

            var timezoneIds = TZConvert.KnownWindowsTimeZoneIds.ToList();
            foreach (var timezoneId in timezoneIds)
            {
                try
                {
                    Timezones.Add(TZConvert.GetTimeZoneInfo(timezoneId));

                }
                catch (Exception e)
                {
                   
                }
                
            }
```

**Comment by mattjohnsonpint** [comment]
Hi.  This is a new time zone ID established in the latest Windows update. Perhaps you don't yet have the update installed on this machine?

Also, if you're targeting .NET 6, you might not need this library anymore.  See [my note in the readme](https://github.com/mattjohnsonpint/TimeZoneConverter#note-on-newer-net-versions).

**Comment by skyguy94** [comment]
We're seeing this issue with similar code as above on .net 48. Please let me know if I'm wrong but I think `KB5000854` is still in preview and isn't widely installed. 

* https://support.microsoft.com/en-us/topic/march-25-2021-kb5000854-os-build-17763-1852-preview-082d35a7-68dd-448a-bfea-03f038669b11
* https://www.catalog.update.microsoft.com/Search.aspx?q=KB5000854

**Comment by mattjohnsonpint** [comment]
Per the [notes in the readme](https://github.com/mattjohnsonpint/TimeZoneConverter#notes):

> Additionally, this library does not attempt to determine if the time zone IDs provided are actually present on the computer where the code is running. It is assumed that the computer is kept current with time zone updates.
>
> For example, if one attempts to convert Africa/Khartoum to a Windows time zone ID, they will get Sudan Standard Time. If it is then used on a Windows computer that does not yet have KB4051956 installed (which created this time zone), they will likely get a TimeZoneNotFoundException.

The same now applies for `Africa/Juba` / `South Sudan Standard Time`

If you have KB5000854 installed, use the latest 3.5.0.  If you don't, stay with 3.4.0.

Sorry if this is painful, but such is the way with time zone updates.  Not everyone gets them all at once.

**Comment by mattjohnsonpint** [comment]
Also see #96 that needed this new Windows zone to be supported.

In general, I try to add them as soon as they are released, regardless of how *widely* released they are.
