### ISSUE TITLE
Conversion question

### ISSUE THREAD

**Issue by chris-zengenti** [mattjohnsonpint/TimeZoneConverter#99]
Hello, and thank you for creating the TimeZoneConverter!

I have an issue, as follows...

Using `TZConvert.IanaToWindows("Europe/Madrid")` generates _"Romance Standard Time"_

Using `TZConvert.WindowsToIana("Romance Standard Time")` generates _"Europe/Paris"_

Is this expected?  Not sure if it's an issue with the library or it's supposed to work.

Thanks!

**Comment by mattjohnsonpint** [comment]
Yes, this is expected.  It's the nature of the two data sets (Windows vs IANA).  The [CLDR mappings](https://github.com/unicode-org/cldr/blob/master/common/supplemental/windowsZones.xml) that bind them look like this:

```xml
<!-- (UTC+01:00) Brussels, Copenhagen, Madrid, Paris -->
<mapZone other="Romance Standard Time" territory="001" type="Europe/Paris"/>
<mapZone other="Romance Standard Time" territory="BE" type="Europe/Brussels"/>
<mapZone other="Romance Standard Time" territory="DK" type="Europe/Copenhagen"/>
<mapZone other="Romance Standard Time" territory="ES" type="Europe/Madrid Africa/Ceuta"/>
<mapZone other="Romance Standard Time" territory="FR" type="Europe/Paris"/>
```

Only the entries marked `"001"` (called the "golden zone") will round trip without knowing the territory (country, region, etc.).

This is also why there's an overload that accepts a territory code.  `TZConvert.WindowsToIana("Romance Standard Time", "ES")` will result in `"Europe/Madrid"`.
